services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
    networks:
      main:
        aliases:
          - 'bank_simulator.api.lan'
  gateway:
    container_name: gateway
    build:
      context: ./app
      platforms:
          - linux/amd64
          - linux/arm64
      args:
          APP_NAME: app
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./app
        target: /usr/local/app
    depends_on:
      - bank_simulator
    networks:
      main:
        aliases:
          - 'gateway.api.lan'
networks:
  main: